# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' This is a function to rapidly fit linear models and return estimated
#' coefficients.
#'
#' @title Estimate coefficients for linear model.
#' @param y A numeric vector of response variables
#' @param X A numeric matrix of predictor variables
#' @return A numeric list with estimated coefficients and standard deviations.
#' @export
fastLm <- function(y, X) {
    .Call('_samSim_fastLm', PACKAGE = 'samSim', y, X)
}

