# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' [[Rcpp::depends(RcppArmadillo)]]
NULL

#' This is a function to rapidly fit linear models and return estimated
#' coefficients.
#'
#' @title Return difference between two time zones at a given date.
#' @param y A numeric vector of response variables
#' @param X A numeric matrix of predictor variables
#' @return A numeric list with estimated coefficients and standard deviations.
#'
#' [[Rcpp::export]]
#' @export
NULL

